name: app_carona_novo
description: Aplicativo Flutter para login, cadastro e caronas.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  email_validator: ^2.0.1
  flutter_native_splash: ^2.4.1
  image_picker: ^1.1.2
  http: ^1.2.2
  
  # Firebase - versões atualizadas para compatibilidade
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.5.1
  firebase_database: ^11.3.10
  firebase_storage: ^12.3.4
  cloud_functions: ^5.1.1
  
  # Provider para gerenciamento de estado
  provider: ^6.1.1

  # Notificações
  firebase_messaging: ^15.1.2
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.3

  # Exportação e compartilhamento de dados
  path_provider: ^2.1.4
  share_plus: ^10.1.2
  
  # Armazenamento local
  shared_preferences: ^2.3.3
  
  # Formatação de datas
  intl: ^0.19.0
  
  # Geolocalização e Mapa
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  google_maps_flutter: ^2.10.0
  url_launcher: ^6.3.1
  
  # Variáveis de ambiente
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env #variáveis de ambiente

  fonts:
    - family: NotoSerif
      fonts:
        - asset: assets/fonts/NotoSerif-Regular.ttf
        - asset: assets/fonts/NotoSerif-Bold.ttf
          weight: 700

flutter_native_splash:
  # === CORES ===
  color_android: "#42a5f5"
  color_dark_android: "#042a49"
  color_ios: "#42a5f5"
  color_dark_ios: "#042a49"
  color_web: "#42a5f5"
  color_dark_web: "#042a49"

  # === IMAGENS PRINCIPAIS ===
  image_android: assets/images/inco_az.png
  image_ios: assets/images/inco_az.png

  # === BACKGROUND PERSONALIZADO ===
  background_image_android: assets/images/background_android.png
  background_image_ios: assets/images/background_ios.png

  # === BRANDING (logo pequena embaixo) ===
  branding_android: assets/images/brand_android.png
  branding_bottom_padding_android: 24
  branding_ios: assets/images/brand_ios.png
  branding_bottom_padding_ios: 24

  # === OUTROS ===
  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: scaleAspectFill

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/inco_az.png
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: assets/images/icone_transp.png




